# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #контейнер с Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    # проброс портов
    ports:
      - "8081:80"
    volumes:
      - ../afisha_project:/data/afisha
    networks:
      - app-network

  #Контейнер с PHP-FPM, назовём его app
  application:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: application # имя контейнера после запуска
    #tty: true
    ports:
      - "5173:5173"
    volumes:
      - ../afisha_project:/data/afisha
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  #Контейнер с БД
  database:
    image: mysql:5.7
    container_name: database # имя контейнера после запуска
    environment:
      MYSQL_DATABASE: ${DB_NAME} # имя нашей БД
      MYSQL_USER: ${DB_USER} # имя пользователя, с которым будет подключаться 
      MYSQL_PASSWORD: ${DB_PASSWORD} # пароль для пользователя
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # администраторский пароль
    ports:
      - "3307:3306"
    # volumes:
    #   - ../laravel/db:/var/lib/mysql
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
